### PR TITLE
[WIP] Add activitivities for the users hands-on session

### PR DESCRIPTION
**Pull request by pulkkins**
- [x] Add general plan for the session contents
- [x] Add description about prerequisites
- [x] Add introduction slides
- [x] Exercises & notebooks: setup pysteps in Colab
- [x] Exercises & notebooks: reading and processing input data
- [x] Exercises & notebooks: optical flow and extrapolation
- [x] Exercises & notebooks: advection interpolation
- [x] Exercises & notebooks: deterministic nowcasts -> verification -> exporting
- [x] Exercises & notebooks: ensemble nowcasts -> verification -> exporting
- [x] Exercises & notebooks: NWP blending
- [ ] Exercises & notebooks: cell tracking

### CODE REVIEW

**Comment by dnerini** [comment]
Very nice work so far! This is going to be great :-)

Few minor comments from my side:
- should we clear the output cells from the notebooks before committing to git? In general, this is considered best practice, but maybe for this case it makes more sense to keep it?
- for the setup (block_01), we could simplify the installation in google colab by using [conda-colab](https://pypi.org/project/condacolab/). What do you think?
- how do you plan to organize the session?

**Comment by RubenImhoff** [comment]
Thanks, @dnerini! 

Regarding your comments:

- I also think it would be better (cleaner) to empty the output cells before committing to git. In any case, we can do this in the final version before merging everything.
- Regarding block01, conda-colab could work as well! This works too, but let's see what Seppo thinks (I have no preference).
- We plan to start with a short introduction talk on using pysteps. Then the participants can go through the blocks and after every block we do a very quick wrap-up.

**Comment by ritvje** [comment]
Hi! About the cell outputs, I think it would be better to keep them in the solution/example notebooks. It would be nice to see the results without running the notebook, as that takes some time.

**Comment by RubenImhoff** [comment]
Good point, @ritvje!

**Comment by pulkkins** [comment]
Using conda-colab for block01 is a good idea. I'll try how that works.

**Comment by pulkkins** [comment]
I have a suggestion about splitting some notebooks into two. This would make sense if there are multiple people contributing to the same notebook, or if there will be two groups of people doing the exercises independently:

- Block 5 contains blending and cell tracking that are separate topics, so this seems obvious to me.
- Block 4 contains both deterministic and probabilistic nowcasts. That could be splitted into two. They have common code (input data processing and optical flow) in the beginning, but that's also included in the previous notebooks. What do you think?
- The above raises a question if we could remove some code from the beginning of block 4 to reduce overlap with block 3?

**Comment by RubenImhoff** [comment]
Sounds good, Seppo, that should be possible! Is it an idea to make a helper to block 4 that basically performs these steps (i.e., the overlapping code with block 3)? 

In addition, the helper to block 5 (blending) now really is more of a starting point to help the participants code (and not just code that you can run on the background to have all the previous steps performed). I'd chosen to do so, because it will speed up the blending tutorial, which should allow the participants to see the possibilities of this module, but not spend too much time on it at the end of the session. Perhaps the helper script fits better in the excercises folder?

**Comment by RubenImhoff** [comment]
By the way, should we also split the exercises in two or leave them together?

**Comment by ritvje** [comment]
I think splitting the exercise 4 in two is a good idea, since we are also splitting the notebooks. 

@RubenImhoff did you upload the latest version of `helper_nowcasting_methods.ipynb`? I am trying to run it in the beginning of the deterministic nowcasting notebook but I can't get similar output as in the probabilistic nowcasting notebook. Also `precip_obs`, `precip_finite`, `motion_field` are not defined after running the notebook, only `precip`.

**Comment by RubenImhoff** [comment]
Indeed, I had forgot to upload the helper as well, the right version should be on it now. 
I'll adjust the exercise 4 to only hold for the probabilistic nowcasting part. :)

**Comment by ritvje** [comment]
I added the notebook & exercise for the deterministic nowcasting. Exporting the nowcasts was an interesting experience. It seems if you forget to close the exporter, you get `PermissionError: [Errno 13]` code when running the code again (which of course makes sense, but it was a bit confusing), so that's something to keep in mind.

Also, we should check that all notebooks have a correct link to open them in Colab before the course, now some of them have a link to some other notebook.

**Comment by RubenImhoff** [comment]
Good idea. Should we put those links in the exercises (or at the end as 'answers')?

**Comment by dnerini** [comment]
Hey all, I need to merge this PR, sorry. Please continue working directly in the main branch.

**Comment by RubenImhoff** [comment]
I didn't add the exporter to the probabilistic nowcasts, by the way. Although it gives some more options with an ensemble, I assumed that the point of the exporter is clear in the deterministic part and that we should not repeat it for the sake of time during the workshop.
Anyway, if we let the participants work on either the deterministic or probabilistic part, it would be could to add it. Let me know what the plan is there. :)

**Comment by RubenImhoff** [comment]
No problem, @dnerini. Let's keep using this PR for discussion points and we can commit directly to the main branch (or make a new PR?).

**Comment by ritvje** [comment]
@dnerini or @pulkkins: regarding the cell tracking exercise: would it be possible to add a new day in the FMI example data for that? The currently available days are not in my opinion well suited for cell tracking (for a simple, clear example anyway), and I am not really familiar with any of the other datasources. Also I think compared to the existing example in the documentation on cell tracking, the only thing we can add is showing the method on new dataset, which requires adjusting the parameters (which is required since FMI images are CAPPI, not max-reflectivity).  

Another option would be to skip that exercise. Probably we would still have enough material for the 2h session without it.

**Comment by dnerini** [comment]
Hey Jenna, sure, it's always possible to add more data, but before that, did you consider using the Swiss example data already employed in the tracking tutorial in our doc?

**Comment by ritvje** [comment]
Yes and that would work. But I am not sure if there would be any added value in the exercise compared to just reading/running the example, since the example is really good.

**Comment by RubenImhoff** [comment]
Letting them do the example - we could discuss on Monday if we can think of any different flavours to that - would work too, of course. Might be interesting for the participants to have the opportunity to get a very brief hands-on experience with the cell tracking.

**Comment by ritvje** [comment]
Let's discuss the exercise on Monday. I will not do anything to the exercise before then and I'll do whatever we decide on Monday after that.

**Pull request merged**
